# Generated by Django 3.2.3 on 2021-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='industry',
            field=models.CharField(choices=[('', 'Choose industry'), ('re', 'Real estate'), ('ht', 'Health'), ('at', 'Atomotive'), ('ft', 'Fitness')], default='', max_length=2),
        ),
    ]
